version: '3.8'

services:
  # Aplicação Spring Boot
  app:
    build: .
    container_name: cidades-esg-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:cidadesdb
    networks:
      - esg-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/cidades/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  esg-network:
    driver: bridge
